name: Vampire
version: 4.3.0
main: com.massivecraft.vampire.P
depend: [mcore1]
permissions:
  vampire.command.intend:
    description: intend to infect others
    default: true
  vampire.command.infect:
    description: infect others that are willing
    default: true
  vampire.command.list:
    description: list the vampires on the server
    default: op
  vampire.command.turn:
    description: instantly turn player
    default: op
  vampire.command.cure:
    description: cure a vampire
    default: op
  vampire.command.setinfection:
    description: set infection (0 to 100)
    default: op
  vampire.command.setfood:
    description: set foodlevel (0 to 20)
    default: op
  vampire.command.version:
    description: check the plugin version
    default: op