main: com.massivecraft.vampire.P
name: vampire
version: 5.2.7
website: http://massivecraft.com/vampire
authors: [Cayorion]
description: §eAnyone can become a vampire, but do you want to? During daytime vampires cower from sunlight. During the night the humans reach for their holy water and wooden stakes as the vampires roam the lands with inhuman strength, speed and levitation-powers. Driven by their endless bloodlust, they devour all living in their way. §aCayorion §efrom the minecraft server §aMassiveCraft §eis the lead programmer. Feel free to visit us at §bhttp://massivecraft.com
depend: [mcore]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  vampire.is.vampire:        {description: An example permission. See the config., default: false}
  vampire.is.human:          {description: An example permission. See the config., default: false}
  vampire.show.self:         {description: show info on yourself, default: false}
  vampire.show.other:        {description: show info on others, default: false}
  vampire.shriek:            {description: shriek, default: false}
  vampire.mode.bloodlust:    {description: use bloodlust, default: false}
  vampire.mode.intent:       {description: use intent to infect, default: false}
  vampire.mode.nightvision:  {description: use nightvision, default: false}
  vampire.altar.dark:        {description: use an altar of darkness, default: false}
  vampire.altar.light:       {description: use an altar of light, default: false}
  vampire.trade.offer:       {description: offer blood to someone, default: false}
  vampire.trade.accept:      {description: accept blood offer, default: false}
  vampire.combat.infect:     {description: be infectious in combat, default: false}
  vampire.combat.contract:   {description: contract infection in combat, default: false}
  vampire.version:           {description: see plugin version, default: false}
  vampire.list:              {description: list vampires and infected, default: false}
  vampire.set:               {description: set player attributes, default: false}
  vampire.set.vampire.true:  {description: instantly turn player, default: false}
  vampire.set.vampire.false: {description: instantly cure a vampire, default: false}
  vampire.set.infection:     {description: set infection (0 to 1), default: false}
  vampire.set.food:          {description: set food (0 to 20), default: false}
  vampire.set.health:        {description: set health (0 to 20), default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  vampire.*:
    children:
      vampire.show.self: true
      vampire.show.other: true
      vampire.shriek: true
      vampire.mode.bloodlust: true
      vampire.mode.intent: true
      vampire.mode.nightvision: true
      vampire.altar.dark: true
      vampire.altar.light: true
      vampire.trade.offer: true
      vampire.trade.accept: true
      vampire.combat.infect: true
      vampire.combat.contract: true
      vampire.version: true
      vampire.list: true
      vampire.set: true
      vampire.set.vampire.true: true
      vampire.set.vampire.false: true
      vampire.set.infection: true
      vampire.set.food: true
      vampire.set.health: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  vampire.kit.op:
    default: op
    children:
      vampire.*: true
  vampire.kit.rank3:
    default: false
    children:
      vampire.kit.rank2: true
  vampire.kit.rank2:
    default: false
    children:
      vampire.kit.rank1: true
      vampire.set: true
      vampire.set.vampire.true: true
      vampire.set.vampire.false: true
      vampire.set.infection: true
      vampire.set.food: true
      vampire.set.health: true
  vampire.kit.rank1:
    default: false
    children:
      vampire.kit.rank0: true
      vampire.show.other: true
      vampire.mode.bloodlust: true
      vampire.list: true
  vampire.kit.rank0:
    default: false
    children:
      vampire.show.self: true
      vampire.shriek: true
      vampire.mode.intent: true
      vampire.mode.nightvision: true
      vampire.altar.dark: true
      vampire.altar.light: true
      vampire.trade.offer: true
      vampire.trade.accept: true
      vampire.combat.infect: true
      vampire.combat.contract: true
      vampire.version: true
  vampire.kit.default:
    default: true
    children:
      vampire.kit.rank0: true