name: Vampire
version: 4.0.0
main: com.massivecraft.vampire.P
permissions:
  vampire.admin:
    description: Give this permission to the admins on the server.
    default: op
    children:
      vampire.command.list: true
      vampire.command.infect: true
      vampire.command.turn: true
      vampire.command.cure: true
      vampire.command.feed: true
  vampire.command.help:
    description: Display help pages
    default: true
  vampire.command.intend:
    description: intend to infect others
    default: true
  vampire.command.list:
    description: List vampires on the server
    default: op
  vampire.command.infect:
    description: set infection (0 to 100)
    default: op
  vampire.command.turn:
    description: instantly turn player
    default: op
  vampire.command.cure:
    description: cure a vampire
    default: op
  vampire.command.feed:
    description: feed a vampire
    default: op